### PR TITLE
support alfred 4 (and later)

### PR DESCRIPTION
**Pull request by karlsander**
This PR changes the module to work with alfred 4, which drops the version postfix from folder and filenames.

It drops support for v3 which is a pretty harsh breaking change, so here's [an alternative PR](https://github.com/SamVerschueren/resolve-alfred-prefs/pull/5) that supports both.

### CODE REVIEW

**Comment by LitoMore** [comment]
Hi @karlsander, I saw you created two pull request, which pull request should I pick up to review?

**Comment by karlsander** [comment]
I created two because I think it‘s a decision the @sindresorhus or @SamVerschueren  should probably make. My preference would be the reckless one (this one) and supporting previous versions has been shut down so maybe the project creators feel the same.

**Comment by LitoMore** [comment]
@karlsander Yes, I commented in another PR. Let's go to that PR for more discussion.

**Comment by SamVerschueren** [comment]
See #8

**Pull request closed without merging**
